LAMMPS data file for CL ions ref:S.J. Halstead, P. An & S. Zhang (2014) Simulations of dissociation constants in low pressure supercritical water, Molecular Physics, 112:17, 2235-2240, DOI: 10.1080/00268976.2014.885093

1 atoms
0 bonds
0 angles
0 dihedrals
1 atom types
0 bond types
0 angle types
0 dihedral types
-4.000000 6.925159 xlo xhi
-4.000000 6.925159 ylo yhi
-4.000000 6.925159 zlo zhi

Masses

1    35.453 #Cl

Pair Coeffs

1   0.118          4.41724

Atoms

1     1    1     -1     1.000     1.00000     0.00000     #Li
